version: 2

models:
  - name: stg_orders
    description: '{{ doc("stg_orders") }}'
    columns:
      - name: order_id
        description: this is order id columns which is having define unique values 
        tests:
          - not_null
          - unique

