version: 2

sources:
  - name: asgn_src
    database: sourcedb
    schema: jshop
    tables:
      - name: customers
      - name: items
      - name: products
      - name: orders
        config:
          freshness:
            warn_after: {count: 1, period: day}
            error_after: {count: 3, period: day}
          loaded_at_field: ordered_at
        tests:
          - not_null
          - unique

